version: '3'
services:
  sanity_check_run:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - pnetwork
    command: ["node", "usr/node/app/puppetfinder.js"]

  refusa_run:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - pnetwork
    command: ["node", "usr/node/app/refusa.js"]
networks:
  pnetwork:
    driver: bridge


