version: '3'
services:
  sanity_check_run:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - pnetwork
    command: ["node", "usr/node/app/puppetfinder.js"]

  refusa_run:
    env_file:
      - variables.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - pnetwork
    command: ["node", "usr/node/app/refusa.js"]

  mass_prop_run:
    env_file:
      - variables.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - pnetwork
    command: ["node", "usr/node/app/mass_prop_finder.js"]

  test_run:
    env_file:
      - variables.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - pnetwork
    command: >
       sh -c "cd usr/node/app/ && mocha"
networks:
  pnetwork:
    driver: bridge


