version: '3'
services:
  sanity_check_run:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - pnetwork
    command: ["node", "usr/node/app/puppetfinder.js"]

  refusa_run:
    environment:
      - LIBRARY_CARD=22400008565125
      - SENDGRID_API_KEY=
      - RESULTS_DESTINATION=Jahmal23@gmail.com
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.aws/:/root/.aws:ro
    ports:
      - "8080:8080"
    networks:
      - pnetwork
    command: ["node", "usr/node/app/refusa.js"]
networks:
  pnetwork:
    driver: bridge


