version: '3'
services:
  puppetrun:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - pnetwork
networks:
  pnetwork:
    driver: bridge
